name: banquet-health-case-challenge

services:
  postgres:
    image: postgres:16
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: local
        POSTGRES_DB: dev
    ports:
        - "5442:5432"
    volumes:
        - postgres:/var/lib/postgresql/data
    networks:
        - banquet-health

volumes:
    postgres:

networks:
  banquet-health:
    driver: bridge
